# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDg3YzU4MzM0YWU2YzA4ZGRlM2I4N2JlNmJkNDI0NDEzNTFmN2E5NjI5Nzg5YTA5Y2I4YzkwNGVhYWI5MDM4YjUzMzU3ZjFlM2JkN2NkOGU0NDQyMzM4YzhjZTMxOTFmZWU4OGNkODAxY2I3YjJjZGIwOTllN2E1MjQ3ODY4YTI=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jhipsterSampleApplication
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: jhipsterSampleApplication
    password:
